### ISSUE TITLE
Attempting to select multiple barcodes breaks everything

### ISSUE THREAD

**Issue by astopy** [zooniverse/Orchids#29]
* Select a barcode
* Click "Select barcode" again, and then click on the image. This leaves a black circle with an "x" as below:

![screen shot 2015-04-23 at 14 51 41](https://cloud.githubusercontent.com/assets/428423/7298548/52b93850-e9c8-11e4-9b69-55dee73c6456.png)

* Click "OK", and this happens:

![screen shot 2015-04-23 at 14 53 18](https://cloud.githubusercontent.com/assets/428423/7298575/81301ed8-e9c8-11e4-9dd3-1fc26ac4d857.png)

(Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17)

**Comment by eatyourgreens** [comment]
Yeah, it automatically switches to the rectangle tool for the label after you've marked a barcode. I should probably give the initial rectangle a default size other than zero!
