### ISSUE TITLE
Identify - field image upload and assignment bug

### ISSUE THREAD

**Issue by johnt2** [zooniverse/Orchids#38]
There are bugs to fix relating to image upload and assignment to users. Users are not receiving new batches of images when they are uploaded, but they are receiving duplicates of images that they have already classified. After a while reclassifying these, users are then being locked out - holding message saying we're waiting for images' appears.

Related to this, we should agree a batch upload frequency (e.g. twice a week) so that we can manage expectations with users.

**Comment by eatyourgreens** [comment]
Pinging @chrissnyder and @parrish on this one. There's a group in the orchid project for uploaded photos taken in the field. @astopy and me have been adding new subjects to that group, in batches of ~35, using the manifests app for ouroboros. There should be 117 active subjects in the group now but
a) the latest batch of 38 subjects isn't activating automatically.
b) people are getting the 'no more subjects' message after classifying ~50 photos (basically, after classifying the initial subject set from around about the project launch.)

Other than generating a manifest, and importing it through the manifests app, is there anything else we need to do to activate new subjects? We're going to be adding new subjects roughly once a week, I'd expect.

**Comment by parrish** [comment]
Looking into it now.  It's possible some of the stats got out of sync when we were having database troubles a week or two ago.

**Comment by parrish** [comment]
Actually, I found a bug that was preventing subject imports in an edge-case.
Let me know if you run into anything like this again.

**Comment by eatyourgreens** [comment]
Hi @parrish have you got time to quickly look at this again?

I added 66 new subjects to the field photos group last week, but they aren't being activated.
https://api.zooniverse.org/projects/orchid/groups/5540f9e599bda504dc000001

**Comment by parrish** [comment]
Looks like the group class had full import turned on: `self.full_import = true`

That works under assumption that once a group is activated it's not going to require further activation.

I disabled it, so you shouldn't have trouble with this any more.
